// ═══ MOCK DATA — Seed missions for UI development ═══

import type { Mision, AppState } from './types';

export const MOCK_MISSIONS: Mision[] = [
  {
    id: 'm1',
    titulo: 'Find 10 vegan restaurants in Puerto Vallarta needing websites',
    descripcion: 'Identify and profile 10 vegan/plant-based restaurants in PV that have no website or a poor-quality website.',
    columna: 'en_ronda',
    prioridad: 'alta',
    esferas: ['research-esfera'],
    subAgentCount: 3,
    tokenCost: 2.4,
    proximoPaso: 'Run scraper on Google Maps PV + Tripadvisor',
    tags: ['research', 'pv', 'outreach-pipeline'],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'm2',
    titulo: 'Design landing page template for restaurant verticals',
    descripcion: 'Create a reusable Awwwards-quality template for restaurant clients in LATAM.',
    columna: 'proximo',
    prioridad: 'alta',
    esferas: ['darya-design'],
    subAgentCount: 0,
    tokenCost: 0,
    udecScore: 8.2,
    proximoPaso: 'Define color palette + typography system for restaurant vertical',
    tags: ['design', 'template', 'latam'],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'm3',
    titulo: 'Deploy 3 client sites to Vercel + configure DNS',
    descripcion: 'Tacos El Güero, Mariscos La Palapa, Vegan Banderas — all need production deploys.',
    columna: 'en_ronda',
    prioridad: 'critica',
    esferas: ['deploy-esfera'],
    subAgentCount: 1,
    tokenCost: 0.8,
    proximoPaso: 'vercel --prod for tacos-el-guero.com',
    tags: ['deploy', 'vercel', 'dns'],
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'm4',
    titulo: 'WhatsApp outreach to 10 PV restaurants',
    descripcion: 'Send personalized WhatsApp messages to restaurant owners with portfolio examples.',
    columna: 'esperando',
    prioridad: 'media',
    esferas: ['outreach-esfera'],
    subAgentCount: 0,
    tokenCost: 0.3,
    proximoPaso: 'Waiting on research-esfera to complete restaurant list',
    tags: ['whatsapp', 'outreach', 'pv'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'm5',
    titulo: 'Generate 5 e-commerce sites for Guadalajara mesa',
    descripcion: 'Build complete Shopify-alternative sites for 5 artisan clothing brands in GDL.',
    columna: 'bandeja',
    prioridad: 'media',
    esferas: ['build-esfera'],
    subAgentCount: 0,
    tokenCost: 0,
    tags: ['build', 'ecommerce', 'gdl'],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'm6',
    titulo: 'Strategy: ARCHON-X client acquisition for Q2',
    descripcion: 'Define the go-to-market strategy for landing 3 ARCHON-X contracts ($5K–$25K each).',
    columna: 'proximo',
    prioridad: 'critica',
    esferas: ['synthia-prime', 'research-esfera', 'outreach-esfera'],
    subAgentCount: 0,
    tokenCost: 0,
    tags: ['strategy', 'archon-x', 'q2', 'council-needed'],
    councilHistory: [],
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'm7',
    titulo: 'Set up Cloudflare Workers for API edge routing',
    descripcion: 'Migrate API layer to Cloudflare Workers for global sub-50ms response times.',
    columna: 'listo',
    prioridad: 'alta',
    esferas: ['deploy-esfera'],
    subAgentCount: 0,
    tokenCost: 1.2,
    tags: ['cloudflare', 'workers', 'performance'],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_APP_STATE: AppState = {
  sphereStatuses: {
    'synthia-prime': 'activa',
    'darya-design': 'descansando',
    'research-esfera': 'trabajando',
    'deploy-esfera': 'trabajando',
    'outreach-esfera': 'esperando' as 'descansando', // mapped to descansando visually
    'build-esfera': 'descansando',
  } as AppState['sphereStatuses'],
  activeMisions: MOCK_MISSIONS,
  subAgents: [],
  councilActive: false,
  viewMode: 'kanban',
  soundMode: 'silent',
  demoMode: false,
  transitionState: 'idle',
};
